package org.asterisk.wishsimulator;

public enum Item
{
    JEAN, QIQI, TIGHNARI, KEQING, MONA, DEHYA, DILUC,
    FARUZAN, SAYU, SHIKANOIN_HEIZOU, SUCROSE, CHONGYUN, DIONA, KAEYA, LAYLA, MIKA, ROSARIA, COLLEI, KAVEH, KIRARA, YAOYAO,
    BEIDOU, DORI, FISCHL, SARA, KUKI_SHINOBU, LISA, RAZOR, GOROU, NINGGUANG, NOELLE, YUNJIN, BARBARA, CANDACE, XINGQIU, AMBER,
    BENNETT, THOMA, XIANGLING, XINYAN, YANFEI,
    AMOS_BOW, SKYWARD_HARP, LOST_PRAYER_TO_THE_SACRED_WINDS, SKYWARD_ATLAS, SKYWARD_PRIDE, WOLFS_GRAVESTONE, PRIMORDIAL_JADE_WINGED_SPEAR,
    SKYWARD_SPINE, AQUILA_FAVONIA, SKYWARD_BLADE,
    FAVONIUS_WARBOW, RUST, SACRIFICIAL_BOW, THE_STRINGLESS, EYE_OF_PERCEPTION, FAVONIUS_CODEX, THE_WIDSITH, FAVONIUS_GREATSWORD,
    RAINSLASHER, SACRIFICIAL_GREATSWORD, THE_BELL, DRAGONS_BANE, FAVONIUS_LANCE, FAVONIUS_SWORD, LIONS_ROAR, SACRIFICIAL_SWORD,
    THE_FLUTE,
    RAVEN_BOW, SHARPSHOOTERS_OATH, SLINGSHOT, EMERALD_ORB, MAGIC_GUIDE, THRILLING_TALES_OF_DRAGON_SLAYERS, BLOODTAINTED_GREATSWORD,
    DEBATE_CLUB, FERROUS_SHADOW, BLACK_TASSEL, COOL_STEEL, HARBINGER_OF_DAWN, SKYRIDER_SWORD
}